import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {useEffect, useState} from "react";
import {Simulate} from "react-dom/test-utils";
import input = Simulate.input;



const Home: NextPage = () => {
    const [hello, setHello] = useState(null);

    useEffect(() => {
        fetch('/api/hello')
            .then(res => res.json())
            .then(setHello)
    }, []);

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/the_game/public/favicon.ico"/>

      </Head>

      <main className={styles.main}>
          <div className={styles.grid}>
              {hello && <h1>{JSON.stringify(hello)}</h1>}
          </div>
        <div className={styles.grid}>
          <Link href={"/cardsList"}>
            <a className={styles.card}>
              <h1>CardsList</h1>
            </a>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href={"/Table"}>
            <a className={styles.card}>
              <h1>Table</h1>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
