# Use the Node.js image as a base image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies in the container
RUN npm ci

# Copy the rest of the files to the container
COPY . .

# Build the Next.js app in the container
RUN npm run build

# Set the environment to development
ENV NODE_ENV=development

# Expose port 3000 for the app to listen on
EXPOSE 3000

# Run the app when the container starts
CMD [ "npm", "run", "dev" ]
